# Generated by Django 4.2 on 2025-11-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'due_date')},
        ),
    ]
